# Generated by Django 5.2.6 on 2025-10-16 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название папки')),
                ('faculty', models.CharField(max_length=100, verbose_name='Факультет')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Предмет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materialfolder', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Папка материалов',
                'verbose_name_plural': 'Папки материалов',
                'ordering': ['faculty', 'course', 'subject', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='materials/', verbose_name='Файл')),
                ('faculty', models.CharField(max_length=100, verbose_name='Факультет')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('type', models.CharField(choices=[('book', 'Книга'), ('notes', 'Конспект'), ('video', 'Видео'), ('presentation', 'Презентация'), ('code', 'Исходный код'), ('other', 'Другое')], max_length=20, verbose_name='Тип материала')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.materialfolder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['-upload_date'],
            },
        ),
    ]
