# Generated by Django 5.2.7 on 2025-10-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialfolder',
            options={'ordering': ['name'], 'verbose_name': 'Папка материалов', 'verbose_name_plural': 'Папки материалов'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='course',
        ),
        migrations.RemoveField(
            model_name='material',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='material',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='materialfolder',
            name='course',
        ),
        migrations.RemoveField(
            model_name='materialfolder',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='materialfolder',
            name='subject',
        ),
    ]
