# Generated by Django 5.2.11 on 2026-03-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_materialfolder_options_remove_material_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('video', 'Видео'), ('audio', 'Аудио'), ('image', 'Изображение'), ('document', 'Документ'), ('text', 'Текст'), ('presentation', 'Презентация'), ('code', 'Исходный код'), ('other', 'Другое')], max_length=20, verbose_name='Тип материала'),
        ),
    ]
