"""
Django settings for msu_portal project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import date
from django.core.exceptions import ImproperlyConfigured
from .env import env_bool, env_csv, env_int

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Only this checkout's local profile; process/Docker environment takes precedence.
load_dotenv(BASE_DIR / '.env', override=False)

# Everything that must survive a redeploy/restart (database, uploaded files, logs)
# lives under one directory so a single persistent disk/volume can be mounted here.
DATA_DIR = Path(os.environ.get('PORTAL_DATA_DIR', BASE_DIR / 'data'))
DATA_DIR.mkdir(parents=True, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = env_bool('DJANGO_DEBUG', True)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY or SECRET_KEY in ('GENERATE_ME', 'your-secret-key-here-change-in-production'):
    if not DEBUG:
        raise ImproperlyConfigured('Set a private DJANGO_SECRET_KEY before production startup.')
    SECRET_KEY = 'django-insecure-local-development-only'

ALLOWED_HOSTS = env_csv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1' if DEBUG else '')
if not DEBUG and (not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS):
    raise ImproperlyConfigured('Set explicit DJANGO_ALLOWED_HOSTS before production startup.')
CSRF_TRUSTED_ORIGINS = env_csv(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'http://localhost:8000,http://127.0.0.1:8000' if DEBUG else '',
)


# дата начала семестра для вычисления чётности недели (можно переопределять в env)
try:
    SEMESTER_START_DATE = date.fromisoformat(os.environ.get('SEMESTER_START_DATE', '2026-01-15'))
except ValueError:
    raise ImproperlyConfigured('SEMESTER_START_DATE must use YYYY-MM-DD.') from None

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # needed for filesizeformat etc.
    'main',
    'schedule',
    'materials',
    'departments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'msu_portal.urls'

# Настройки шаблонов
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'msu_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_PATH', DATA_DIR / 'db.sqlite3'),
        'OPTIONS': {
            'timeout': env_int('DATABASE_TIMEOUT', 20),
        }
    }
}

# Compose uses separate credentials, avoiding URL-escaping problems in passwords.
if os.environ.get('DATABASE_ENGINE', '') not in ('', 'sqlite', 'postgresql'):
    raise ImproperlyConfigured('DATABASE_ENGINE must be sqlite or postgresql.')
if os.environ.get('DATABASE_ENGINE') == 'postgresql':
    for variable in ('POSTGRES_DB', 'POSTGRES_USER', 'POSTGRES_PASSWORD'):
        if not os.environ.get(variable) or os.environ[variable] == 'GENERATE_ME':
            raise ImproperlyConfigured(f'Set {variable} for PostgreSQL.')
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['POSTGRES_DB'],
        'USER': os.environ['POSTGRES_USER'],
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {'connect_timeout': 10},
    }
elif os.environ.get('DATABASE_URL') and os.environ.get('DATABASE_ENGINE') != 'sqlite':
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
    )
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Настройки статических файлов
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration for static files
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media/')

AUTH_USER_MODEL = 'main.CustomUser'

# Authentication settings
AUTHENTICATION_BACKENDS = [
    'main.backends.StudentIDBackend',
]
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

# Email verification / recovery. Local development prints letters to the terminal.
# Set a real SMTP backend and sender in the environment on Yandex Cloud.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = env_int('EMAIL_PORT', 587, maximum=65535)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured('Enable only one of EMAIL_USE_TLS and EMAIL_USE_SSL.')
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Учебный портал ВМК МГУ <noreply@localhost>')
PORTAL_PUBLIC_URL = os.environ.get('PORTAL_PUBLIC_URL', 'http://127.0.0.1:8000' if DEBUG else '')
PASSWORD_RESET_TIMEOUT = 3600

# --- Security hardening (applies mainly when DEBUG is False) ---
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', True) and not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
X_FRAME_OPTIONS = 'DENY'

# Additional security settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Enable only behind a proxy that overwrites X-Real-IP; Compose binds web to loopback.
TRUST_PROXY_CLIENT_IP = env_bool('DJANGO_TRUST_PROXY_CLIENT_IP', False)

# One stream for all workers; Docker handles rotation outside the processes.
# Gunicorn/Nginx access logging stays off; diagnostic logs must also stay private.
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO').strip().upper()
if LOG_LEVEL not in ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'):
    raise ImproperlyConfigured('LOG_LEVEL must be DEBUG, INFO, WARNING, ERROR or CRITICAL.')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {'handlers': ['console'], 'level': LOG_LEVEL},
    'loggers': {
        'django': {'handlers': ['console'], 'level': LOG_LEVEL, 'propagate': False},
    },
}
