# Generated by Django 5.2.11 on 2026-02-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.IntegerField(default=0, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='faculty',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Факультет'),
        ),
    ]
