# Generated by Django 5.2.11 on 2026-02-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('headman', 'Староста'), ('teacher', 'Преподаватель'), ('media', 'Медиа (может публиковать новости)'), ('uploader', 'Загрузчик (может добавлять материалы и папки)'), ('admin', 'Администратор')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
