# Generated by Django 5.2.11 on 2026-02-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='number',
            field=models.IntegerField(blank=True, help_text='Например: 105', null=True, verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.IntegerField(help_text='Определяется по первой цифре номера группы', verbose_name='Курс'),
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['faculty', 'course', 'number'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('number', 'faculty')},
        ),
    ]
