# Generated by Django 5.2.6 on 2025-10-16 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='assigned_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата задания'),
        ),
    ]
