# Generated by Django 5.2.7 on 2025-10-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20251016_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='teacher_id',
            new_name='first_teacher_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='second_teacher_id',
            field=models.CharField(max_length=50, null=True, verbose_name='ID Преподавателя'),
        ),
    ]
