# Generated by Django 5.2.7 on 2025-10-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_rename_teacher_id_schedule_first_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='another_classroom',
            field=models.CharField(max_length=50, null=True, verbose_name='Прочие Аудитория'),
        ),
    ]
