# Generated by Django 5.2.7 on 2025-10-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedule_another_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='first_teacher_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя Первого Преподавателя'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='second_teacher_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя Второго Преподавателя'),
        ),
    ]
