# Generated by Django 5.2.7 on 2025-10-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedule_first_teacher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time_end',
            field=models.CharField(max_length=20, null=True, verbose_name='Время окончания'),
        ),
    ]
