# Generated by Django 5.2.11 on 2026-03-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='week_parity',
            field=models.CharField(choices=[('all', 'Все недели'), ('odd', 'Нечётные недели'), ('even', 'Чётные недели')], default='all', help_text='Относительно начала семестра', max_length=4, verbose_name='Чётность недели'),
        ),
    ]
