# Generated by Django 5.2.11 on 2026-09-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_schedule_week_parity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
    ]
