# Generated by Django 5.2.11 on 2026-09-23 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_remove_subject_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='schedule.homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'homework'), name='unique_homework_completion')],
            },
        ),
        migrations.CreateModel(
            name='LessonChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата занятия')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Отменить занятие')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('end', models.TimeField(verbose_name='Окончание')),
                ('classroom', models.CharField(max_length=50, verbose_name='Аудитория')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='Причина / пояснение')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_changes', to='schedule.schedule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.subject', verbose_name='Предмет')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'date'), name='unique_lesson_change_date')],
            },
        ),
    ]
