"""One-time, transactional import into an empty, migrated PostgreSQL database."""
from copy import deepcopy
from contextlib import closing
from importlib import import_module
from pathlib import Path
import sqlite3
import uuid

from django.apps import apps
from django.conf import settings
from django.core.management import call_command
from django.core.management.base import BaseCommand, CommandError
from django.db import connections, transaction, DatabaseError
from django.db.migrations.executor import MigrationExecutor


# Permissions/content types are regenerated by migrate. Sessions and temporary
# email challenges are deliberately dropped when moving to a new signing key.
EXCLUDED = ('contenttypes.contenttype', 'auth.permission', 'sessions.session',
            'main.pendingsignup', 'main.emailratelimit')
SOURCE_ALIAS = 'sqlite_import'


def transfer_models():
    return [m for m in apps.get_models() if m._meta.managed
            and not m._meta.proxy and m._meta.label_lower not in EXCLUDED]


def require_current_schema(alias):
    executor = MigrationExecutor(connections[alias])
    executor.loader.check_consistent_history(connections[alias])
    if executor.migration_plan(executor.loader.graph.leaf_nodes()):
        raise CommandError(f'{alias}: pending migrations. Migrate a COPY of the source first; see docs/docker-postgres.md.')


def require_empty_target():
    """Never merge into a live portal, even when only seed departments exist."""
    Department = apps.get_model('departments', 'Department')
    for model in apps.get_models():
        if model._meta.label_lower in {'contenttypes.contenttype', 'auth.permission', 'departments.department'}:
            continue
        if model._meta.managed and not model._meta.proxy and model._base_manager.using('default').exists():
            raise CommandError(f'Target is not empty ({model._meta.label}). Import refused; no overwrite option exists.')
    seed = import_module('departments.migrations.0002_load_departments').DEPARTMENTS
    fields = [field.attname for field in Department._meta.concrete_fields]
    expected = {row['id']: {name: getattr(Department(**row), name) for name in fields} for row in seed}
    for row in Department.objects.using('default').values(*fields):
        if row != expected.get(row['id']):
            raise CommandError('Target has edited departments. Import refused.')


class Command(BaseCommand):
    help = 'Import SQLite into EMPTY PostgreSQL. Keeps a consistent SQLite backup and rolls back on failure.'

    def add_arguments(self, parser):
        parser.add_argument('source', type=Path)
        parser.add_argument('--dry-run', action='store_true', help='Back up, validate and export only; do not change PostgreSQL.')

    def handle(self, *args, **options):
        if connections['default'].vendor != 'postgresql':
            raise CommandError('Target must be PostgreSQL. Use the Docker web service, not local SQLite settings.')
        source = options['source'].resolve()
        if not source.is_file():
            raise CommandError('Source SQLite file does not exist.')
        require_current_schema('default')
        require_empty_target()
        destination = Path(settings.DATA_DIR) / 'backups' / f'sqlite-import-{uuid.uuid4().hex}'
        destination.mkdir(parents=True, mode=0o700)
        snapshot = destination / 'source.sqlite3'
        fixture = destination / 'portal.json'
        # SQLite's backup API includes committed WAL data without editing source.
        with closing(sqlite3.connect(source.as_uri() + '?mode=ro', uri=True)) as original:
            with closing(sqlite3.connect(snapshot)) as backup:
                original.backup(backup)
                if backup.execute('PRAGMA integrity_check').fetchall() != [('ok',)]:
                    raise CommandError('SQLite integrity check failed. Source was not changed.')
                if backup.execute('PRAGMA foreign_key_check').fetchone():
                    raise CommandError('SQLite contains broken foreign keys. Source was not changed.')
        snapshot.chmod(0o600)
        source_settings = deepcopy(connections.databases['default'])
        source_settings.update(ENGINE='django.db.backends.sqlite3', NAME=snapshot.as_uri() + '?mode=ro',
                               OPTIONS={'uri': True}, CONN_MAX_AGE=0, CONN_HEALTH_CHECKS=False)
        connections.databases[SOURCE_ALIAS] = source_settings
        try:
            require_current_schema(SOURCE_ALIAS)
            models = transfer_models()
            expected = {m._meta.label_lower: m._base_manager.using(SOURCE_ALIAS).count() for m in models}
            call_command('dumpdata', database=SOURCE_ALIAS, exclude=EXCLUDED, use_natural_foreign_keys=True,
                         use_base_manager=True, output=str(fixture), verbosity=0)
            fixture.chmod(0o600)
            if options['dry_run']:
                self.stdout.write(self.style.SUCCESS('Validation passed. PostgreSQL unchanged.'))
            else:
                with transaction.atomic(using='default'):
                    # Serializes two accidental simultaneous imports and excludes
                    # writers during the emptiness check/import. Stop web first.
                    tables = [m._meta.db_table for m in apps.get_models(include_auto_created=True)
                              if m._meta.managed and not m._meta.proxy]
                    with connections['default'].cursor() as cursor:
                        cursor.execute("SET LOCAL lock_timeout = '10s'")
                        quoted = ', '.join(connections['default'].ops.quote_name(t) for t in sorted(set(tables)))
                        cursor.execute(f'LOCK TABLE {quoted} IN EXCLUSIVE MODE')
                    require_empty_target()
                    apps.get_model('departments', 'Department').objects.all().delete()
                    call_command('loaddata', str(fixture), database='default', verbosity=0)
                    for model in models:
                        label = model._meta.label_lower
                        if model._base_manager.count() != expected[label]:
                            raise CommandError(f'Count mismatch in {label}; transaction rolled back.')
                    connections['default'].check_constraints()
                self.stdout.write(self.style.SUCCESS('Import committed. Row counts and foreign keys verified.'))
            for label, count in sorted(expected.items()):
                self.stdout.write(f'{label}: {count}')
            self.stdout.write(f'Private backup/export directory: {destination}')
            self.stdout.write('Media files are NOT in the database. Keep/copy data/media separately. Sessions and pending email codes were excluded.')
        except DatabaseError as exc:
            # Database exceptions can contain personal field values. Do not log them.
            raise CommandError(f'Import failed ({type(exc).__name__}); target transaction rolled back. Private backup: {destination}') from None
        finally:
            connections[SOURCE_ALIAS].close()
            del connections[SOURCE_ALIAS]
            connections.databases.pop(SOURCE_ALIAS, None)
